### ISSUE TITLE
Drop message is buggy with Artifact of Swarms on

### ISSUE THREAD

**Issue by mikotastic** [william-hollywood/ThatWasMine#1]
If you enable Artifact of Swarms and Sacrifice with this mod on, it shows an AI enemy as the killer
![image](https://user-images.githubusercontent.com/101668172/158453928-8f03a938-d054-4cbf-8caf-131e4c8769af.png)

**Comment by william-hollywood** [comment]
Heyo,
Did this happen on a level with a void seed by any chance? I have experienced this myself with voidtouched enemies and larva (when a larva hits the ground and explodes it counts as a kill).

This mod works by hooking into where a sacrifice item is spawned in, I am just checking the damage report for what causes the enemy to die and drop an item.

I don't see this as an issue with swarms, but I can make the mod only prompt for player kills by default and add a config to enable messages for drops from other sources.

**Comment by mikotastic** [comment]
This happens on the first stage without a void seed
Making it prompt with only the player kill would be nice though

**Comment by william-hollywood** [comment]
Hmm, I'll look into it. It could have been fall damage or something. But the updated version should fix it regardless.
